apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"type":"local"},"name":"tvshows-hdd"},"spec":{"accessModes":["ReadWriteMany"],"capacity":{"storage":"3.6Ti"},"hostPath":{"path":"/media/tvshows"},"storageClassName":"manual"}}
    pv.beta.kubernetes.io/gid: "1000"
  creationTimestamp: "2021-08-24T12:37:57Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    type: local
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:phase: {}
    manager: k3s
    operation: Update
    time: "2021-08-24T12:37:57Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:type: {}
      f:spec:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:hostPath:
          .: {}
          f:path: {}
          f:type: {}
        f:persistentVolumeReclaimPolicy: {}
        f:storageClassName: {}
        f:volumeMode: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-08-24T12:37:57Z"
  name: tvshows-hdd
  resourceVersion: "147652"
  uid: fccc84a0-a1bc-4b65-bfb8-41f4b21cdd31
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 3958241859993600m
  hostPath:
    path: /media/tvshows
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
status:
  phase: Available
